#ifndef SSD1306_COMMANDS_H
#define SSD1306_COMMANDS_H

#define OLED_SET_CONTRAST 0x81
#define OLED_ENTIRE_DISPLAY_ON 0xA5
#define OLED_ENTIRE_DISPLAY_RESUME 0xA4
#define OLED_NORMAL_DISPLAY 0xA6
#define OLED_INVERT_DISPLAY 0xA7
#define OLED_DISPLAY_OFF 0xAE
#define OLED_DISPLAY_ON 0xAF

#define OLED_DEACTIVATE_SCROLL 0x2E
#define OLED_ACTIVATE_SCROLL 0x2F
#define OLED_SET_VERTICAL_SCROLL_AREA 0xA3
#define OLED_RIGHT_HORIZONTAL_SCROLL 0x26
#define OLED_LEFT_HORIZONTAL_SCROLL 0x27
#define OLED_VERTICAL_RIGHT_SCROLL 0x29
#define OLED_VERTICAL_LEFT_SCROLL 0x2A

#define OLED_SET_MEMORY_MODE 0x20
#define OLED_SET_COLUMN_ADDR 0x21
#define OLED_SET_PAGE_ADDR 0x22
#define OLED_SET_PAGE_START_ADDR 0xB0 // Base command, add page number (0-7) to get 0xB0-0xB7

#define OLED_SET_START_LINE 0x40
#define OLED_SET_SEGMENT_REMAP_0 0xA0
#define OLED_SET_SEGMENT_REMAP_1 0xA1
#define OLED_SET_MULTIPLEX_RATIO 0xA8
#define OLED_SET_COM_SCAN_INC 0xC0
#define OLED_SET_COM_SCAN_DEC 0xC8
#define OLED_SET_DISPLAY_OFFSET 0xD3
#define OLED_SET_COM_PINS 0xDA

#define OLED_SET_DISPLAY_CLOCK_DIV 0xD5
#define OLED_SET_PRECHARGE 0xD9
#define OLED_SET_VCOM_DETECT 0xDB

#define OLED_CHARGE_PUMP 0x8D

#define OLED_RMW_START 0xE0
#define OLED_RMW_END 0xEE

#define OLED_WIDTH 128
#define OLED_HEIGHT 64

#endif // SSD1306_COMMANDS_H
